### ISSUE TITLE
Provide an option for the Registry to load register values from a YAML file

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal/pycyphal#249]
The YAML file should be of the Yakut/Yukon export format without the node-ID; that is:

```yaml
uavcan.sub.readiness.id:            10
uavcan.sub.setpoint_dyn.id:         21
uavcan.sub.setpoint_vel.id:         22
uavcan.sub.setpoint_r_volt.id:      23
uavcan.sub.setpoint_r_torq.id:      24
uavcan.sub.setpoint_r_volt_u9.id:   25
uavcan.sub.setpoint_r_torq_u9.id:   26

uavcan.pub.feedback.id:             100
uavcan.pub.dynamics.id:             110
uavcan.pub.power.id:                120
uavcan.pub.status.id:               130
uavcan.pub.compact.id:              140
uavcan.pub.dq.id:                   150
uavcan.pub.temp.id:                 160

uavcan.srv.low_level_io.id:         10
```
